-- MySQL Script generated by MySQL Workbench
-- Wed Nov 23 21:52:36 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Companhia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Companhia` (
  `id` INT NULL,
  `nome` VARCHAR(255) NULL,
  `cnpj` VARCHAR(14) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Aviao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Aviao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(255) NOT NULL,
  `modelo` VARCHAR(255) NULL,
  `prefixo` VARCHAR(3) NULL,
  `capacidade` INT NULL,
  `id_companhia` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Aviao_Companhia1_idx` (`id_companhia` ASC) VISIBLE,
  CONSTRAINT `fk_Aviao_Companhia1`
    FOREIGN KEY (`id_companhia`)
    REFERENCES `mydb`.`Companhia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Hangar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Hangar` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `local` VARCHAR(255) NOT NULL,
  `id_aviao` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Hangar_Aviao_idx` (`id_aviao` ASC) VISIBLE,
  CONSTRAINT `fk_Hangar_Aviao`
    FOREIGN KEY (`id_aviao`)
    REFERENCES `mydb`.`Aviao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`helicoptero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`helicoptero` (
  `id` INT NOT NULL,
  `marca` VARCHAR(255) NULL,
  `modelo` VARCHAR(255) NULL,
  `cor` VARCHAR(255) NULL,
  `capacidade` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pista` (
  `id` INT NOT NULL,
  `numero` VARCHAR(225) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Jato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Jato` (
  `id` INT NOT NULL,
  `marca` VARCHAR(255) NULL,
  `modelo` VARCHAR(255) NULL,
  `cor` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Voo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Voo` (
  `id` INT NOT NULL,
  `numero` VARCHAR(255) NULL,
  `data` VARCHAR(8) NULL,
  `hora` VARCHAR(4) NULL,
  `origem` VARCHAR(3) NULL,
  `destino` VARCHAR(3) NULL,
  `piloto` VARCHAR(255) NULL,
  `conpiloto` VARCHAR(255) NULL,
  `observacao` VARCHAR(255) NULL,
  `id_aviao` INT NOT NULL,
  `id_aviao` INT NOT NULL,
  `id_jato` INT NOT NULL,
  `id_helicoptero` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Voo_Aviao1_idx` (`id_aviao` ASC) VISIBLE,
  INDEX `fk_Voo_Pista1_idx` (`id_aviao` ASC) VISIBLE,
  INDEX `fk_Voo_Jato1_idx` (`id_jato` ASC) VISIBLE,
  INDEX `fk_Voo_helicoptero1_idx` (`id_helicoptero` ASC) VISIBLE,
  CONSTRAINT `fk_Voo_Aviao1`
    FOREIGN KEY (`id_aviao`)
    REFERENCES `mydb`.`Aviao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Voo_Pista1`
    FOREIGN KEY (`id_aviao`)
    REFERENCES `mydb`.`Pista` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Voo_Jato1`
    FOREIGN KEY (`id_jato`)
    REFERENCES `mydb`.`Jato` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Voo_helicoptero1`
    FOREIGN KEY (`id_helicoptero`)
    REFERENCES `mydb`.`helicoptero` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

